albums/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
	url(r'^$', views.album_list, name='album_list'),
	url(r'^(?P<id>\d+)/$', views.album_detail, name='album_detail'),
    url(r'^(?P<id>\d+)/edit$', views.album_edit, name='album_edit'),
    url(r'^new/$', views.album_new, name='album_new'),
]

core/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
	url(r'^$', views.index, name='index')
]

flutetunes/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^albums/', include('albums.urls', namespace='albums')),
    url(r'^tracks/', include('tracks.urls', namespace='tracks')),
    url(r'^', include('core.urls', namespace='core')),
]

tracks/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
	url(r'^$', views.track_list, name='track_list'),
	url(r'^artists/$', views.artist_list, name='artist_list'),
	url(r'^genres/$', views.genre_list, name='genre_list'),
	url(r'^(?P<id>\d+)/$', views.track_detail, name='track_detail'),
    url(r'^(?P<id>\d+)/edit$', views.track_edit, name='track_edit'),
    url(r'^new/$', views.track_new, name='track_new'),

	url(r'^artists/(?P<id>\d+)/$', views.artist_detail, name='artist_detail'),
	url(r'^genres/(?P<id>\d+)/$', views.genre_detail, name='genre_detail'),

]

albums/models.py
from django.db import models
from django.core.urlresolvers import reverse

class Album(models.Model):
    title = models.CharField(max_length = 50)
    description = models.TextField (blank=True)

    class Meta:
        ordering = ['title']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('albums:album_detail', args=[self.pk])

core/models.py
from django.db import models

# Create your models here.

playlists/models.py
from django.db import models

# Create your models here.

tracks/models.py
from django.db import models
from django.core.urlresolvers import reverse


class Track(models.Model):

    title =models.CharField(max_length =100,blank=True)
    album = models.ForeignKey('albums.Album',null=True,blank=True)
    artists = models.ManyToManyField('Artist',blank=True)
    genres = models.ManyToManyField('Genre',blank=True)    
    track_number = models.CharField(max_length=10,null=True,blank=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('tracks:track_detail', args=[self.pk])

class Artist(models.Model):

    name =models.CharField(max_length =100)

    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return reverse('tracks:artist_detail', args=[self.pk])


class Genre(models.Model):

    name =models.CharField(max_length =100)

    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return reverse('tracks:genre_detail', args=[self.pk])

albums/forms.py
from django import forms
from .models import Album
from core.forms import BootstrapFormMixin

class AlbumForm(BootstrapFormMixin, forms.ModelForm):

    class Meta:
        model = Album
        fields = ('title','description',)

core/forms.py
from django.forms import widgets

class BootstrapFormMixin(object):
    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)

        for field in self.fields.values():
            if (isinstance(field.widget,widgets.TextInput) or isinstance(field.widget,widgets.Textarea)):

                field.widget.attrs.update({
                    "class":"form-control",
                    })

tracks/forms.py
from django import forms
from .models import Track
from core.forms import BootstrapFormMixin

class TrackForm(BootstrapFormMixin, forms.ModelForm):

    class Meta:
        model = Track
        fields = ('title','album','artists','genres','track_number',)

albums/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.db.models import Count
from django.contrib import messages

from .models import Album
from .forms import AlbumForm

def album_list(request):
	albums = Album.objects.all()

	context = {
		"albums": albums,
	}
	return render(request, "albums/album_list.html", context)

def album_detail(request, id):
	album = get_object_or_404(Album, pk=id)
	tracks = album.track_set.all()

	context = {
		"album": album,
		"tracks": tracks,
	}

	return render(request, "albums/album_detail.html", context)

def album_new(request):

	if request.method == "POST":
		form = AlbumForm(request.POST)
		if form.is_valid():
			album = form.save()
			messages.success(request,"Album created!")
			return redirect("albums:album_detail",id=album.pk)
	else:
		form = AlbumForm()

	context = {
		"form":form,
	}
	return render(request,"albums/album_edit.html",context)

def album_edit(request,id):
	album = get_object_or_404(Album,pk=id)

	if request.method == "POST":
		form = AlbumForm(request.POST, instance=album)
		if form.is_valid():
			album = form.save()
			messages.success(request,"Album updated!")
			return redirect("albums:album_detail",id=album.pk)
	else:
		form = AlbumForm(instance=album)

	context = {
		"form":form,
		"album":album,
	}
	return render(request,"albums/album_edit.html",context)

core/views.py
from django.shortcuts import render
from django.http import HttpResponse

def index(request):
	return render(request, "core/index.html")

playlists/views.py
from django.shortcuts import render

# Create your views here.

tracks/views.py
from django.shortcuts import render, get_object_or_404,redirect
from django.http import HttpResponse
from django.db.models import Count
from django.contrib import messages

from .models import Artist, Genre, Track
from .forms import TrackForm

def track_list(request):
	tracks = Track.objects.all()

	context = {
		"tracks": tracks,
	}
	return render(request, "tracks/track_list.html", context)

def track_detail(request, id):
	track = get_object_or_404(Track, pk=id)
	artists = track.artists.all()
	genres = track.genres.all()
	context = {
		"track": track,
		"artists":artists,
		"genres":genres,

	}

	return render(request, "tracks/track_detail.html", context)

def track_new(request):

	if request.method == "POST":
		form = TrackForm(request.POST)
		if form.is_valid():
			track = form.save()
			messages.success(request,"Track created!")
			return redirect("tracks:track_detail",id=track.pk)
	else:
		form = TrackForm()

	context = {
		"form":form,
	}
	return render(request,"tracks/track_edit.html",context)

def track_edit(request,id):
	track = get_object_or_404(Track,pk=id)

	if request.method == "POST":
		form = TrackForm(request.POST, instance=track)
		if form.is_valid():
			track = form.save()
			messages.success(request,"Track updated!")
			return redirect("tracks:track_detail",id=track.pk)
	else:
		form = TrackForm(instance=track)

	context = {
		"form":form,
		"track":track,
	}
	return render(request,"tracks/track_edit.html",context)

def artist_list(request):
	artists = Artist.objects.all()

	context = {
		"artists": artists,
	}
	return render(request, "tracks/artist_list.html", context)

def artist_detail(request, id):
	artist = get_object_or_404(Artist, pk=id)
	tracks = artist.track_set.all()

	context = {
		"tracks": tracks,
		"artist":artist,
	}

	return render(request, "tracks/artist_detail.html", context)

def genre_list(request):
	genres = Genre.objects.all()

	context = {
		"genres": genres,
	}
	return render(request, "tracks/genre_list.html", context)
def genre_detail(request, id):
	genre = get_object_or_404(Genre, pk=id)
	tracks = genre.track_set.all()
	context = {
		
		"genre":genre,
		"tracks": tracks,
	}

	return render(request, "tracks/genre_detail.html", context)

albums/templates/albums/album_detail.html
{% extends "core/base.html" %}

{% block content %}
    <h2>{{album.title}}</h2>

    {% if tracks %}
        
        <hr>
        <div class="row">        	
        		
        	{% include "tracks/track_list.html" %}	
        	
        </div>
    
    {% endif %}

    <a class="btn btn-primary btn-block btn-lg" href="{% url 'albums:album_new'%}">
        Add new Album
    </a>
{% endblock content %}

albums/templates/albums/album_edit.html
{% extends "core/base.html" %}

{% block content %}
    {% if album %}
        <h2>
            Edit:{{album.title}}
        </h2>
    {% else %}
        <h2>
            New Album
        </h2>
    {% endif %}


    <form action="" method="POST">
        {% csrf_token %}
        
        {% for field in form %}
            {% include "core/_form_input.html" %}
        {% endfor %}

        <button type="submit" class="btn btn-primary btn-block btn-lg">
            Save
        </button>
    </form>

{% endblock content %}

albums/templates/albums/album_list.html
{% extends "core/base.html" %}

{% block content %}
	<h2>Albums</h2>
	<div class="panel-group" id="accordion" role="tablist">
		{% for album in albums %}
			<div class="panel panel-default">
				<div class="panel-heading" id="heading-{{album.pk}}">
					<h4 class="panel-title">				
						<a 
							class="collapsed" 
							href="#collapse-{{album.pk}}"
							data-toggle="collapse"
							data-parent="accordion"
						>
							{{album.title|title}}
						</a>
					</h4>
				</div>
				<div id="collapse-{{album.pk}}" class="panel-collapse collapse">
					<div class="panel-body">
						{% if album.description %}
							{{album.description}}
						{% else %}
							<small><em>This album has no description</em></small>
						{% endif %}
						<p>
							<a href="{{ album.get_absolute_url }}">View Album</a>
						</p>
					</div>
				</div>
			</div>
		{% endfor %}
	</div>
	
    <a class="btn btn-primary btn-block btn-lg" href="{% url 'albums:album_new'%}">
        Add new Album
    </a>
{% endblock content %}

core/templates/core/_form_input.html
<div 
    {% if field.errors %}
        class="form-group has-error"
    {% else %} 
    class="form-group"
    {% endif %}>
    
        {{field.label_tag}}
        {{field}}

    {% if field.errors %}
    <span class="help-block">
    {% for error in field.errors%}
        {{error}}
    {% endfor %}
    </span>
    {% endif %}
</div>

core/templates/core/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <title>
        {% block title %}
            Flute Tunes
        {% endblock title %}
    </title>
    <!-- Latest compiled and minified CSS -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <script src="https://use.fontawesome.com/a04d9e4c1c.js"></script>

    <link rel="stylesheet" type="text/css" href="{% static 'core/styles.css' %}" />
</head>
<body>
    <header>
        <nav class="navbar navbar-color navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed navbar-default" data-toggle="collapse" data-target="#navbar-header-collapse" aria-expanded="false">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a href="{% url 'core:index' %}" class="navbar-brand">
                        <p>
                            <i class="fa fa-music" aria-hidden="true"></i>
                            Flute Tunes
                        </p>
                    </a>
                </div>
                <div class="collapse navbar-collapse" id="navbar-header-collapse">

                    <form class="navbar-form navbar-right" action="{% url 'albums:album_list' %}">
                        <label for="index-search" class="sr-only">Search album</label>
                        <input type="text" id="index-search" class="form-control" name="q" placeholder="Find an album">    
                        <button type="submit" class="btn btn-info">Submit</button>
                    </form>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
    <div class="{% block content_classes %}main-content {% endblock content_classes%}">
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-success">
    {{ message }}
    </div>
    {% endfor %}
    {% endif %}
    <div class="container">
        {% block content %}

        {% endblock %}
    </div>
    </div>
    </div>

    <footer class="page-footer">
        <hr>
        <div class="container">
            &copy; Awesome Inc U. Bootcamp 2016
        </div>

    </footer>

    <script   src="https://code.jquery.com/jquery-3.1.0.min.js"   integrity="sha256-cCueBR6CsyA4/9szpPfrX3s49M9vUU5BgtiJj06wt/s="   crossorigin="anonymous"></script>
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</body>
</html>

core/templates/core/index.html
{% extends "core/base.html" %}

{% block content %}
	<div class="jumbotron jumbotron-index">
		<h1>Flute Tunes</h1>
	</div>
	<div class="row">
		<div class="col-sm-6 col-offset-sm-3">
			<a href="{% url 'albums:album_list' %}" class="thumbnail">
				View Albums
				<img src="http://img.lum.dolimg.com/v1/images/open-uri20150422-20810-1n258vh_16b93145.jpeg?region=0,0,600,600&width=320">
			</a>
		</div>
		<div class="col-sm-6 col-offset-sm-3">
			<a href="{% url 'tracks:track_list' %}" class="thumbnail">
				View Tracks
				<img src="http://img.lum.dolimg.com/v1/images/open-uri20150422-20810-1n258vh_16b93145.jpeg?region=0,0,600,600&width=320">
			</a>
		</div>
	</div>
	<div class="row">
		<div class="col-sm-6 col-offset-sm-3">
			<a href="{% url 'tracks:artist_list' %}" class="thumbnail">
				View Artists
				<img src="http://img.lum.dolimg.com/v1/images/open-uri20150422-20810-1n258vh_16b93145.jpeg?region=0,0,600,600&width=320">
			</a>
		</div>
		<div class="col-sm-6 col-offset-sm-3">
			<a href="{% url 'tracks:genre_list' %}" class="thumbnail">
				View Genres
				<img src="http://img.lum.dolimg.com/v1/images/open-uri20150422-20810-1n258vh_16b93145.jpeg?region=0,0,600,600&width=320">
			</a>
		</div>
	</div>

{% endblock content %}

tracks/templates/tracks/artist_detail.html
{% extends "core/base.html" %}

{% block content %}
    <h2>{{artist.name}}</h2>

    {% if tracks %}
        
        <hr>
        
        <h4>Tracks:</h4> 
        {% for track in tracks %}
        Title: {{track.title}} <br>
        Album: {{track.album}}<br><br>
        {% endfor %}     	
        	 
    
    {% endif %}
 
{% endblock content %}

tracks/templates/tracks/artist_list.html
{% extends "core/base.html" %}

{% block content %}
	<h2>Artists</h2>
	<div class="panel-group" id="accordion" role="tablist">
		{% for artist in artists %}
			<div class="panel panel-default">
				<div class="panel-heading" id="heading-{{artist.pk}}">
					<h4 class="panel-title">				
						<a 
							class="collapsed" 
							href="#collapse-{{artist.pk}}"
							data-toggle="collapse"
							data-parent="accordion"
						>
							{{artist.name|title}}
						</a>
					</h4>
				</div>
				<div id="collapse-{{artist.pk}}" class="panel-collapse collapse">
					<div class="panel-body">
						{% if artist.description %}
							{{artist.description}}
						{% else %}
							<small><em>This artist has no description</em></small>
						{% endif %}
						<p>
							<a href="{{artist.get_absolute_url }}">View Artist</a>
						</p>
					</div>
				</div>
			</div>
		{% endfor %}
	</div>
{% endblock content %}

tracks/templates/tracks/genre_detail.html
{% extends "core/base.html" %}

{% block content %}
    <h2>{{genre.name}}</h2>

    {% if tracks %}
        
        <hr>
        
        <h4>Tracks:</h4> 
        {% for track in tracks %}
        Title: {{track.title}} <br>
        Album: {{track.album}}<br><br>
        {% endfor %}     	
        	 
    
    {% endif %}
 
{% endblock content %}

tracks/templates/tracks/genre_list.html
{% extends "core/base.html" %}

{% block content %}
	<h2>Genres</h2>
	<div class="panel-group" id="accordion" role="tablist">
		{% for genre in genres %}
			<div class="panel panel-default">
				<div class="panel-heading" id="heading-{{genre.pk}}">
					<h4 class="panel-title">				
						<a 
							class="collapsed" 
							href="#collapse-{{genre.pk}}"
							data-toggle="collapse"
							data-parent="accordion"
						>
							{{genre.name|title}}
						</a>
					</h4>
				</div>
				<div id="collapse-{{genre.pk}}" class="panel-collapse collapse">
					<div class="panel-body">
						{% if genre.description %}
							{{genre.description}}
						{% else %}
							<small><em>This genre has no description</em></small>
						{% endif %}
						<p>
							<a href="{{ genre.get_absolute_url }}">View Genre</a>
						</p>
					</div>
				</div>
			</div>
		{% endfor %}
	</div>
{% endblock content %}

tracks/templates/tracks/track_detail.html
{% extends "core/base.html" %}

{% block content %}
    <h2>
    <div class="pull-right">
        <a href="{% url 'tracks:track_edit' track.pk%}">
        <i class="fa fa-pencil-square" aria-hidden="true"></i>
        </a>
    </div>
    {{track.title}}
    </h2>
	<h4>Album:</h4> {{track.album}}
    {% if track.artists %}
        
        <hr>
        
        <h4>Artists:</h4> 
        {% for artist in artists %}
        {{artist.name}}
        {% endfor %}

    
    {% endif %}
    {% if genres %}
        
        <hr>
        <h4>Genres:</h4>
        {% for genre in genres %}
        {{genre.name}}
        {% endfor %}     	
        	
    
    {% endif %}
    
{% endblock content %}

tracks/templates/tracks/track_edit.html
{% extends "core/base.html" %}

{% block content %}
    {% if track %}
        <h2>
            Edit:{{track.title}}
        </h2>
    {% else %}
        <h2>
            New Track
        </h2>
    {% endif %}


    <form action="" method="POST">
        {% csrf_token %}
        
        {% for field in form %}
            {% include "core/_form_input.html" %}
        {% endfor %}

        <button type="submit" class="btn btn-primary btn-block btn-lg">
            Save
        </button>
    </form>

{% endblock content %}

tracks/templates/tracks/track_list.html
{% extends "core/base.html" %}

{% block content %}
	<h2>Tracks</h2>
	<div class="panel-group" id="accordion" role="tablist">
		{% for track in tracks %}
			<div class="panel panel-default">
				<div class="panel-heading" id="heading-{{track.pk}}">
					<h4 class="panel-title">				
						<a 
							class="collapsed" 
							href="#collapse-{{track.pk}}"
							data-toggle="collapse"
							data-parent="accordion"
						>
							{{track.title|title}}
						</a>
					</h4>
				</div>
				<div id="collapse-{{track.pk}}" class="panel-collapse collapse">
					<div class="panel-body">
						{% if track.description %}
							{{track.description}}
						{% else %}
							<small><em>This track has no description</em></small>
						{% endif %}
						<p>
							<a href="{{ track.get_absolute_url }}">View Track</a>
						</p>
					</div>
				</div>
			</div>
		{% endfor %}
	</div>
	<a href="{% url 'tracks:track_new' %}" class="btn btn-primary btn-block btn-lg">Add new track</a>
{% endblock content %}